# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Call for Papers
    url: /call
    weight: 10
  - name: Committees
    url: /committees
    weight: 20
#  - name: Program
#    url: /#program
#    weight: 30
#  - name: Registration
#    url: /registration
#    weight: 40
#  - name: Social Events
#    url: /#top
#    weight: 50
#  - name: Local Information
#    url: /#top
#    weight: 60
#  - name: Accommodation
#    url: /#top
#    weight: 70
#  - name: Sponsors
#    url: /#top
#    weight: 80
  - name: Contact us
    url: 'mailto:pscc2026@sps-lab.org'
    weight: 90
