# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.
# Docs: https://gohugo.io/content-management/menus/#define-in-site-configuration

main:
  - name: Call for Papers
    url: /#top
    weight: 10
  - name: Committees
    url: /#top
    weight: 20
  - name: Program
    url: /#top
    weight: 30
  - name: Registration
    url: /#top
  - name: Social Events
    url: /#top
  - name: Local Information
    url: /#top
  - name: Accommodation
    url: /#top
  - name: Sponsors
    url: /#top
  - name: Contact us
    url: /#top
